# Generated by Django 5.1.3 on 2025-01-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='relation',
        ),
    ]
