# Generated by Django 5.1.7 on 2025-03-14 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.RemoveField(
            model_name='discountbasketdetails',
            name='discount_basket',
        ),
        migrations.RemoveField(
            model_name='discountbasketdetails',
            name='product',
        ),
        migrations.DeleteModel(
            name='DiscountBasket',
        ),
        migrations.DeleteModel(
            name='DiscountBasketDetails',
        ),
    ]
