# Generated by Django 5.1.3 on 2025-03-14 01:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'کوپن تخفیف', 'verbose_name_plural': 'کوپن ها'},
        ),
        migrations.AlterModelOptions(
            name='discountbasket',
            options={'verbose_name': 'سبد تخفیف', 'verbose_name_plural': 'سبد های تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='discountbasketdetails',
            options={'verbose_name': 'جزئیات سبد تخفیف'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد کوپن'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='discount_title',
            field=models.CharField(max_length=100, verbose_name='عنوان سبد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='discountbasket',
            name='start_date',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='discountbasketdetails',
            name='discount_basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_basket_details1', to='discounts.discountbasket', verbose_name='سبد تخفیف'),
        ),
    ]
