# Generated by Django 5.1.7 on 2025-03-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_alter_coupon_options_alter_discountbasket_options_and_more'),
        ('discounts', '0003_initial'),
    ]

    operations = [
    ]
