# Generated by Django 5.1.7 on 2025-03-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='Warehouse_type',
            new_name='warehouse_type',
        ),
    ]
