# Generated by Django 5.1.6 on 2025-03-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='PaymentType',
        ),
    ]
