# Generated by Django 5.1.7 on 2025-03-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_discount'),
        ('orders', '0003_order_description_order_payment_type'),
    ]

    operations = [
    ]
