# Generated by Django 5.1.7 on 2025-04-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20250324_2354'),
        ('orders', '0004_order_order_state'),
    ]

    operations = [
    ]
